#!/usr/bin/env bash
#install nginx and prints Hello World string


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | sudo tee  /var/www/html/index.nginx-debian.html
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
    	return 301 http://www.youtube.com/;
}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
